digits:
  size_of_page: 10
gender:
  range: [0, 1]
  choice_0: 0
  choice_1: 1
place:
  range: [1, 2, 3]
  city_1: 1
  city_2: 2
  city_3: 3
age:
  range: [20, 49]
page_add:
  home: "home"
date: "%H:%M %d/%m/%Y"
